app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/
Route::get('about', ['as' => 'about', 'uses' => 'HomeController@about']);

Route::get('login', ['as'=>'login', 'uses' => 'HomeController@loginWithGoogle']);
Route::get('logout', ['as'=>'logout', function()
{
	Auth::logout();
	return Redirect::route('homepage');
}]);

Route::get('/', ['as'=>'homepage', 'uses' => 'NoteController@index']);

Route::group(['before' => 'auth'], function(){
	Route::resource('note', 'NoteController', ['except' => 'index']);

	Route::get('/import-tags', ['as'=>'import.tags', 'uses' => 'HomeController@ImportTags']);
	Route::get('/import-notes', ['as'=>'import.notes', 'uses' => 'HomeController@ImportNotes']);
});

app/models/Note.php
<?php

class Note extends \Eloquent {
	protected $fillable = ['title', 'content', 'tomboy_id'];

	public static $rules = [
				'title' => 'required',
			];

	public function tags()
	{
		return $this->belongsToMany('Tag');
	}

	public function author()
	{
		return $this->hasOne('User', 'id', 'author_id');
	}
}

app/controllers/NoteController.php
<?php

class NoteController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /note
	 *
	 * @return Response
	 */
	public function index()
	{
		//
		if (Auth::check()){
			if ( !Input::has('searchterm') && empty(Input::get('searchterm')) ){
				$notes = Note::where('author_id', Auth::user()->id)
					->orderBy('created_at', 'DESC')
					->paginate(15);	
			} else {
				$searchterm = Input::get('searchterm');
				Session::flash('message', 'Showing search results for ' . $searchterm);
				$notes = Note::where('title', 'LIKE', '%'.$searchterm.'%')
					->where('content', 'LIKE', '%'.$searchterm.'%', 'OR')
					->orderBy('created_at', 'DESC')
					->paginate(15);	
			}

			if ( Input::has('tag') && !empty(Input::get('tag')) ){
				$tag = Tag::where('name', Input::get('tag'))->first();
				$notes = $tag->notes->sortByDesc('created_at');
			}

			if ( $notes->count() === 0 ){
				$notes = array();
			}
			
		} else {
			$notes = array();
		}
		
		return View::make('notes.index')->withNotes($notes);
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /note/create
	 *
	 * @return Response
	 */
	public function create()
	{
		//
		return View::make('notes.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /note
	 *
	 * @return Response
	 */
	public function store()
	{
		//
		if ( Auth::check() ) {
			$input = Input::all();

			$validation = Validator::make($input, Note::$rules);
			if ( $validation->passes() ){
				// create new note
				$note = new Note;
				$note->title = $input['title'];
				$note->content = $input['content'];
				$note->author_id = Auth::user()->id;
				$note->save();

				if (Input::has('tags') && !empty(Input::get('tags'))){
					$note->tags()->sync(Input::get('tags'));
				}

				Session::flash('message', 'Saved note: ' . $note->title);
				return Redirect::route('homepage');
			} else {
				return Redirect::back()
					->withInput()
					->withErrors($validation)
					->with('message', 'There were validation errors');
			}

		} else {
			return Redirect::route('homepage');
		}
		

	}

	/**
	 * Display the specified resource.
	 * GET /note/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /note/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
		$note = Note::find($id);
		return View::make('notes.edit', compact('note'));
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /note/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//

		$note = Note::find($id);		
		$inputs = Input::all();

		if ($note->update($inputs)){
			if (Input::has('tags') && !empty(Input::get('tags'))){
				$note->tags()->sync(Input::get('tags'));
			} else {
				$note->tags()->sync([]);
			}
			Session::flash('message', 'Updated note: '. $note->title);	
		} else {
			Session::flash('message', 'Could not note: '. $note->title);
		}
		
		return Redirect::back();
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /note/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
		Note::destroy($id);
		Session::flash('message', 'Removed note #' . $id);
		return Redirect::back();
	}

}

app/views/notes/create.blade.php
@extends('layouts.master')

@section('page_title', 'Create Note')

@section('content')
<div class="container">
	<div class="jumbotron">
		<div class="container">
						
			{{ Form::open(['route' => 'note.store', 'role'=>'form'])}}
				<legend>Create Note</legend>
			
				<div class="form-group">
					<label for="title">Title</label>
					<input type="text" class="form-control" id="title" name="title" placeholder="Lorem ipsum...">
				</div>

				<div class="form-group">
					<label for="content">Content</label>
					<textarea class="form-control" id="content" name="content" rows="10" placeholder="Type your note here"></textarea>
				</div>

				<div class="checkbox">
					@foreach(Tag::all()->sortBy('name') as $tag)
					<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
						<label>
							<input type="checkbox" name="tags[]" value="{{$tag->id}}">
							{{$tag->name}}
						</label>	
					</div>					
					@endforeach
				</div>
				
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hgap">
					{{ Form::button('Save', ['type'=>'submit', 'class' => 'btn btn-primary btn-sm'])}}
				</div>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop

app/views/notes/edit.blade.php
@extends('layouts.master')

@section('page_title', 'Edit ')

@section('content')
<div class="container">
	<div class="jumbotron">
		<div class="container">						
			{{Form::model($note,['method'=>'patch','route'=>['note.update', $note->id]])}}
				<legend>Edit Note</legend>
			
				<div class="form-group">
					<label for="title">Title</label>					
					{{Form::text('title',null,['class'=>'form-control'])}}
				</div>

				<div class="form-group">
					<label for="content">Content</label>
					
					{{Form::textarea('content',null,['class'=>'form-control', 'rows'=>'10'])}}
				</div>

				<div class="checkbox">
					@foreach(Tag::all()->sortBy('name') as $tag)
					<div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
						<label>
							@if ( $note->tags->contains($tag->id))
							<input checked="checked" type="checkbox" name="tags[]" value="{{$tag->id}}">
							@else
							<input type="checkbox" name="tags[]" value="{{$tag->id}}">
							@endif
							{{$tag->name}}
						</label>	
					</div>					
					@endforeach
				</div>
				
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 hgap">
					{{ Form::button('Update', ['type'=>'submit', 'class' => 'btn btn-primary btn-sm'])}}
					<a href="{{route('homepage')}}" class='btn btn-info btn-sm'>Back to Notes</a>
				</div>
			{{ Form::close() }}
		</div>
	</div>
</div>
@stop

app/views/notes/index.blade.php
@extends('layouts.master')

@section('page_title', 'Home')

@section('content')
<div class="container">
	
	@if (!empty($notes) )
	@if (method_exists($notes, 'links'))		
		{{ $notes->appends(['searchterm' => Input::get('searchterm')])->links() }}	
	@endif
	
	
		<?php 
			$toggle = 'in'; 
			$panel = 'info';
		?>

		@foreach($notes as $note)		
			<div class="panel panel-{{$panel}}">
				  <div class="panel-heading" data-toggle="collapse" data-target="#{{$note->id}}">
						<h3 class="panel-title">#{{$note->id}} {{$note->title}} 
							<span class='pull-right'>
								@foreach($note->tags as $tag)
									<!-- <button type="button" class="btn btn-primary btn-xs">{{$tag->name}}</button> -->
									<a class="btn btn-primary btn-xs" href="{{route('homepage',['tag'=>$tag->name])}}">{{$tag->name}}</a>
								@endforeach
								
								{{ $note->created_at->diffForHumans() }}
							</span>

						</h3>

				  </div>
				  <div class="panel-body collapse {{$toggle}}" id="{{$note->id}}">
				  		
						<pre id="content{{$note->id}}"><i class="fa fa-quote-left fa-3x pull-left "></i>{{$note->content}}</pre>
						
						
						
						{{ Form::open(['route'=>['note.destroy', $note->id], 'method' => 'delete'])}}
						<a href="{{route('note.edit',['id'=>$note->id])}}" class="btn btn-info btn-xs"><i class="fa fa-pencil fa-fw"></i> Edit</a>						
						<button type="submit" onclick="return confirm('Are you sure you want to delete this note?');" class="btn btn-danger btn-xs"><i class="fa fa-remove fa-fw"></i> Delete</button>
						{{ Form::close() }}
						{{$note->tomboy_id}}
				  </div>
			</div>
		<?php 
			$toggle = ''; 
			$panel = ($panel == 'info'? 'warning':'info');
		?>
		@endforeach
	@if (method_exists($notes, 'links'))		
		{{ $notes->appends(['searchterm' => Input::get('searchterm')])->links() }}	
	@endif		
		
	@else

		<div class="jumbotron">
			<div class="container">
				<h1>Welcome to TBird Notes</h1>
				@if (Auth::check())
				<p>You haven't created any notes yet, click on the button below to create your first note.</p>
				<p>					
					{{ link_to_route('note.create', 'Create Note', null, ['class' => 'btn btn-primary btn-lg'])}}
				</p>
				@else
				<p>Please sign-in to create and view you previous notes.</p>
				<p>					
					{{ link_to_route('login', 'Sign-in', null, ['class' => 'btn btn-primary btn-lg'])}}
				</p>
				@endif
			</div>
		</div>

	@endif
</div>
	
@stop